[user]
enable_graphics = true
enable_random_maze = false
menu_enable = true
sound_enable = false

[graphics]
width = 720
height = 720
fps = 60
title = "PacMan"
maze_path = "assets/data/maze.txt"

[game]
game_speed = 5
pacman_lives = 3
super_mode_duration = 10
scatter_duration = 6
chase_duration = 5

[maze]
width = 39
height = 39
density = 0.8
seed = -1
intersection_step = 3
is_symetric = false
random_maze_path = "assets/data/random.txt"

[genetic]
genetic_enable = true
move_path = "assets/data/moves.txt"
population_size = 100
graded_retain_percentage = 0.2
mutation_chance = 0.1
