[user]
enable_graphics = true
enable_random_maze = false
menu_enable = true
sound_enable = true

[graphics]
width = 720
height = 480
fps = 60
title = "PacMan"
maze_path = "assets/data/maze.txt"

[game]
game_speed = 5
pacman_lives = 3

[maze]
<<<<<<< HEAD
width = 30
height = 30
density = 1
=======
width = 24
height = 24
density = 0.8
>>>>>>> f7d4969222622b2df28e8b311d05e673e88c8aad
seed = -1
intersection_step = 3
is_symetric = false
random_maze_path = "assets/data/random.txt"