[user]
enable_graphics = true
enable_random_maze = true
enable_menu = true

[graphics]
width = 800
height = 800
fps = 60
title = "PacMan"
maze_path = "assets/data/maze.txt"

[game]
game_speed = 5
pacman_lives = 3

[maze]
width = 30
height = 30
density = 0.8
seed = -1
intersection_step = 3
is_symetric = false
random_maze_path = "assets/data/random.txt"