[user]
enable_graphics = true
enable_random_maze = false
menu_enable = true
sound_enable = true

[graphics]
width = 1080
height = 720
fps = 60
title = "PacMan"
maze_path = "assets/data/maze.txt"

[game]
game_speed = 5
pacman_lives = 3
super_mode_duration = 10

[maze]
width = 24
height = 24
density = 0.8
seed = -1
intersection_step = 3
is_symetric = true
random_maze_path = "assets/data/random.txt"