[user]
enable_graphics = true
enable_random_maze = false
menu_enable = false
sound_enable = false

[graphics]
width = 720
height = 720
fps = 60
title = "PacMan"
maze_path = "assets/data/maze.txt"

[game]
game_speed = 5
pacman_lives = 3
super_mode_duration = 10
scatter_duration = 6
chase_duration = 20

[maze]
width = 15
height = 15
density = 0.8
seed = 1
intersection_step = 3
is_symetric = false
random_maze_path = "assets/data/random.txt"

[genetic]
genetic_enable = false
move_path = "assets/data/moves.txt"
population_size = 20
graded_retain_percentage = 0.4
mutation_chance = 0.25
deletion_chance = 0.05
addition_chance = 0.80
replacement_chance = 0.25
selection_type = "tournament"
population_type = ""
max_generation = 50

[neural]
train_enable = false
play_enable = false
output_dir = "assets/model_output/pacman"
weights_path = "weights_1000.hdf5"
state_size = 230
action_size = 4
batch_size = 64
episodes = 100001
learning_rate = 0.03

[policy]
train_enable = true
play_enable = false
alpha = 0.0001
gamma = 0.997
n_actions = 4
episodes = 100001
output_dir = "assets/model_output/pacman"
weights_path = "weights_1000.h5"